package domain

import (
	"context"
	"fmt"
	"net/url"
	"regexp"

	validation "github.com/go-ozzo/ozzo-validation/v4"
)

// Device transports. APNs is the historical default; Bark devices carry a
// synthetic token (generated by the tweak on builds signed without the
// aps-environment entitlement) and receive notifications via an HTTP POST to
// TransportEndpoint (a Bark push URL like https://api.day.app/<device_key>).
const (
	DeviceTransportAPNS = "apns"
	DeviceTransportBark = "bark"
)

type Device struct {
	ID                int64
	APNSToken         string
	Sandbox           bool
	Transport         string `json:"transport"`
	TransportEndpoint string `json:"transport_endpoint"`
	// URLScheme is the custom URL scheme of the app that registered, used
	// for the deep link a Bark notification opens on tap. Empty means
	// Apollo's own "apollo"; other clients (e.g. Phoebus) send theirs so a
	// tap doesn't land in Apollo when both apps are installed.
	URLScheme string `json:"url_scheme"`
}

var urlSchemePattern = regexp.MustCompile(`^[a-z][a-z0-9+.-]*$`)

// DeepLinkScheme is the scheme Bark tap links use for this device.
func (dev *Device) DeepLinkScheme() string {
	if dev.URLScheme == "" {
		return "apollo"
	}
	return dev.URLScheme
}

func (dev *Device) IsBark() bool {
	return dev.Transport == DeviceTransportBark
}

func (dev *Device) Validate() error {
	return validation.ValidateStruct(dev,
		validation.Field(&dev.APNSToken, validation.Required, validation.Length(64, 200)),
		validation.Field(&dev.Transport, validation.In(DeviceTransportAPNS, DeviceTransportBark)),
		validation.Field(&dev.URLScheme, validation.Length(0, 32), validation.Match(urlSchemePattern)),
		validation.Field(&dev.TransportEndpoint, validation.By(func(interface{}) error {
			if !dev.IsBark() {
				return nil
			}
			u, err := url.Parse(dev.TransportEndpoint)
			if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
				return fmt.Errorf("must be an http(s) URL for bark devices")
			}
			return nil
		})),
	)
}

type DeviceRepository interface {
	GetByID(ctx context.Context, id int64) (Device, error)
	GetByAPNSToken(ctx context.Context, token string) (Device, error)
	GetInboxNotifiableByAccountID(ctx context.Context, id int64) ([]Device, error)
	GetWatcherNotifiableByAccountID(ctx context.Context, id int64) ([]Device, error)
	GetByAccountID(ctx context.Context, id int64) ([]Device, error)

	CreateOrUpdate(ctx context.Context, dev *Device) error
	Update(ctx context.Context, dev *Device) error
	Create(ctx context.Context, dev *Device) error
	Delete(ctx context.Context, token string) error
	SetNotifiable(ctx context.Context, dev *Device, acct *Account, inbox, watcher, global bool) error
	GetNotifiable(ctx context.Context, dev *Device, acct *Account) (bool, bool, bool, error)
}
